# -*- coding: utf-8 -*-
"""olá mundo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbRMH4JVkSPUOjfySNC65w0uDhToNOqw
"""

print("Olá Mundo")