# -*- coding: utf-8 -*-
"""poesia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QwvYZKMCOZgwHgS6aPguE9iO70ZpkGvS
"""

print("De tudo, ao meu amor serei atento")
print("Antes, e com tal zelo, e sempre, e tanto")
print("Que mesmo em face do maior encanto")
print("Dele se encante mais meu pensamento.")